### ISSUE TITLE
Sentry making server crash

### ISSUE THREAD

**Issue by diablo14** [Geforce132/SecurityCraft#164]
So when ever y try to place a sentry on the server me and my friends are at, it crashes.

**Comment by bl4ckscor3** [comment]
Are you using the latest version of SecurityCraft (v1.8.18.1 for Minecraft 1.14.4/1.15.2 and v1.8.18.2 for Minecraft 1.12.2)? If not, please update and check if the crash is still happening. If so, post the crash-report.
When reporting crashes, _always_ include the crash-report. Without it, us developers can do next to nothing in order to try and fix the crash. You can find it in the `crash-reports` folder, in the same place where the `mods` folder is.

**Comment by bl4ckscor3** [comment]
Closing this as there is not enough information. If you can provide it, feel free to comment.
