### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Hippigamer** [Geforce132/SecurityCraft#174]
Hello there, I wanted to ask why there is no 1.9 version of Security craft, could you please answer!

**Comment by bl4ckscor3** [comment]
1. This issue tracker is not for general questions about this mod, it is for reporting bugs and, well, issues.
2. Our version scheme changed due to incorrect planning after we released v1.8.3. It's since been that way, and it will probably stay like that. In the end, the version does not matter, it's just a name for something.
