### ISSUE TITLE
Huge FPS drop with the security camera screens . Also some suggestions and optimizations .

### ISSUE THREAD

**Issue by crunkazcanbe** [Geforce132/SecurityCraft#19]
As the Title says . With one or two cameras the FPS drop is not noticeable ,but over 5 camera screens the FPS takes a huge hit . When going over 5 screens the FPS will drop about 15FPS per screen . So with 8 screens running I am getting a whooping 10~9FPS when my average FPS is around 240FPS . This is the only mod installed . I guess the lookingglass mod is highly unoptimized ;because 10FPS is unbearable ,and if I can not have a wall of screens or at least 5 or so screens running at the same time I don't find the cameras worth using ;because my ultimate dream was to build a mansion ,and put a camera in each and every room ,and have 1 secret room with a wall of screens showing each and every room .  Is there anything you can do to optimize the FPS ? Also I noticed the more camera screens you have the faster it makes the camera pan. Is that a bug ? Or can it be fixed ?

Also I would love a config option to change the camera panning speed ,because as with what the speed is now you have a very short time to see something before it turns . Also A config option to make the camera not move at all aka static would be nice . I would prefer another whole version of the camera rather then the config option ;because I would like the option of having a camera that pans in some spots and a static still camera in other spots . Also another version of a camera that just pans up and down would be nice . Also another cool version of a camera I would love to see is a camera that you can right click to open a GUI and put in a name of a person that if the camera sees it can put out a Redstone signal into the block the camera is attached to . This way you could activate something that the camera sees with Redstone . :)

**Comment by bl4ckscor3** [comment]
The FPS drop is something with LookingGlass, we need to see if we can do something about that, since the mod is open source. As for the faster cameras, I _think_ we got that fixed for the next version, but I'm not sure.

For the suggestions, we implemented new customizable options into the Module GUI of each block, maybe we can add some options there to modify a camera's speed.

**Comment by crunkazcanbe** [comment]
Well the version I am using of this mod is compiled from the source as of right now off of here. :) And when you have to many cameras the cameras pan way to fast I mean it's back and forth like 5 times ever couple of seconds.

**Comment by bl4ckscor3** [comment]
1. The increasing speed and FPS drops are caused by LookingGlass, it's not our job to fix it.
2. An option for the camera speed has been added in v1.8.1.
3. An option to stop the camera panning has been added in v1.8.2.4

As for the other options, there might be plans to implement something like this in the future, but for the moment it's a no.
