### ISSUE TITLE
Securitycraft Items disappear

### ISSUE THREAD

**Issue by Arbiter267** [Geforce132/SecurityCraft#197]
I am hosting a server on Aternos, I run the TLauncher and have downloaded the SecurityCraft mod. I join the server and i can see all the new items exist but everytime I am trying to put any item it instantly disappears.

**Comment by bl4ckscor3** [comment]
Install SecurityCraft on your server as well (put the mod file into the `mods` folder) and start the server with the `forge-blablabla.jar` file, _not_ with the `minecraft_server_blabla.jar` file.
As we use this issue tracker for bug reports, and since this is not an issue with the mod, I will close this. If you need further assistance, feel free to join our Discord server.
