### ISSUE TITLE
[1.16.3] [Render thread/ERROR]: Found a broken recipe: net.geforcemods.securitycraft.compat.jei.ReinforcerRecipe@7ace37d1 Outputs: net.minecraft.item.ItemStack: [[1 air minecraft:air]]

### ISSUE THREAD

**Issue by ProsperCraft** [Geforce132/SecurityCraft#208]
[11:14:50] [Render thread/ERROR]: Found a broken recipe: net.geforcemods.securitycraft.compat.jei.ReinforcerRecipe@7ace37d1
Outputs: net.minecraft.item.ItemStack: [[1 air minecraft:air]]  Inputs:  net.minecraft.item.ItemStack: [[1 reinforced_yellow_stained_glass securitycraft:reinforced_yellow_stained_glass]]
 java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air

Stacktrace-
https://gist.github.com/ProsperCraft/119ba3dcb13133aa635a5980a91da18b

Full log-
https://gist.github.com/ProsperCraft/33e72612a237803ad114191e96e8b2b0

[1.16.3] SecurityCraft v1.8.20.1.jar

**Comment by bl4ckscor3** [comment]
How can I reproduce this? Simply starting a client/server does not yield the error and the recipes involving reinforced yellow stained glass shows up fine.

**Comment by ProsperCraft** [comment]
We have not found a way to reproduce it , it happens without any specific actions on our part.

Here is the pack, it may be a mod interaction- [TownCraft TWO for 1.16.3](https://www.curseforge.com/minecraft/modpacks/towncraft)

**Comment by ProsperCraft** [comment]
Digging through logs, it appears to be systemic, and I will have to do mod elimination to find who is causing this - 

https://gist.github.com/ProsperCraft/7ccdfbd95b3437ce618417c187f9947b

**Comment by ProsperCraft** [comment]
It looks like any time a recipe is broken it crafts to air.

**Comment by bl4ckscor3** [comment]
Closing this, as it seems like it's an issue that is caused by another mod. If you can narrow it down to SecurityCraft being the culprit, please comment again with reproduction steps, so we can figure out why this is happening.
If it helps, I have added some more verbose output to the reinforcer recipe. Instead of `Found a broken recipe: net.geforcemods.securitycraft.compat.jei.ReinforcerRecipe@7ace37d1` it should now tell you something along the lines of `Found a broken recipe: Reinforcer Recipe - Vanilla Block: minecraft:dirt - Reinforced Block: securitycraft:reinforced_dirt`. This is not in a released version, so you would have to download/clone this repository, and run `gradlew build` to get a jar file of the mod with this change (it will be in `build/libs` after the build task is done).
