### ISSUE TITLE
[Suggestion] Sections for Security Craft Manual

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Geforce132/SecurityCraft#209]
I have a suggestion for the manual book. It should be divided into sections since going trough 72 pages is a lot and it's hard to remember where exactly in the book certain items are. It could probably have sections for sensors and scanners, locks, decoration blocks, tools, modules, weapons, miscellaneous. Don't get me wrong the current manual is pretty good, but this is just an idea to makes things easier for players who are new to this mod. 

Also here is an example from another mod with sections
![2020-11-03_18 51 37](https://user-images.githubusercontent.com/50182206/98053038-aeb99600-1e05-11eb-9822-bb0fd4f023f0.png)

And here is what is within each section
![2020-11-03_18 51 55](https://user-images.githubusercontent.com/50182206/98053066-c264fc80-1e05-11eb-817f-f0ee99cf2139.png)

Then the rest can be exactly like the book you currently have in this mod.

**Comment by bl4ckscor3** [comment]
I strongly agree, that this will be beneficial. However, we would need to completely rewrite the manual and think about the best way to structure it, which does take its time. I'm leaving this open, because I do want to work on it at some point, but for now at least, the book pages are alphabetically sorted (since v1.8.17 of the mod) so that it's a little easier to find what you're looking for.

**Comment by bl4ckscor3** [comment]
After an internal discussion, we decided that it's not worth creating sections for the manual. We don't have diverse enough content to be able to create useful sections.
