### ISSUE TITLE
Error retinal scanners

### ISSUE THREAD

**Issue by andresfierro** [Geforce132/SecurityCraft#222]
When **using the retinal scanner**, **the fps drops completely,** causing a lot of lag

**Comment by bl4ckscor3** [comment]
The retinal scanner works fine for me. You could try turning off the retinalScannerFace configuration option and see if that helps you. If not, then perhaps something else in your area is causing the lag. If you create a new flatland world and only put a retinal scanner down and using it doesn't affect your performance, the cause is something else.

**Comment by bl4ckscor3** [comment]
I will close this, as we cannot reproduce it. Since there has not been a reply in a week, I'm assuming that this was resolved on your end.
