### ISSUE TITLE
Inventory Scanner not working

### ISSUE THREAD

**Issue by RealSourceOfficial** [Geforce132/SecurityCraft#249]
### Issue
Inventory Scanner For some reason it's not working

### Details
When I walk into the scanner with the items in my inventory it doesn't give a output whatsoever. really annoying because I'm trying to make a map and I want to use inventory scanners

### Extra Information
Block: Inventory Scanner
Modules: Redstone Module
Prohibited Item: Dirt
Tried Solutions: 1 Block above ground, on ground, east-west, north-south, restarting game, restarting PC
Gamemode: Creative
Difficulty: Normal
Game Version: 1.16.5
Mod Version: v1.8.21.1

**Comment by bl4ckscor3** [comment]
Thanks for this detailed report, but you are missing one important piece of information: The version number of the mod (for example v1.8.21). This helps us mod developers know, whether the bug is already fixed, and in the case of it not being fixed, pinpoint it to potential changes that might be the cause of the bug.

However in this case, I am assuming you yourself are walking through the Inventory Scanner that you placed. The reason that nothing is happening is because Inventory Scanners ignore their owners. This is the case with a lot of SecurityCraft's blocks.

**Comment by RealSourceOfficial** [comment]
Ah thanks, I didn't know that the block ignores its owner.
