### ISSUE TITLE
(Suggestion) Redstone Module for Lasers

### ISSUE THREAD

**Issue by drghnio** [Geforce132/SecurityCraft#267]
Make that you can toggle the Lasers and else with redstone

**Comment by bl4ckscor3** [comment]
Lasers already use redstone as an output signal when someone walks through them, it's not possible to add a redstone input because of that. You can already toggle lasers by rightclicking the laser block with a Universal Block Modifier and clicking the respective button on the side, but I do realize that that can only be done manually and there's no way to automate this action.
I'm afraid, this won't be added.

**Comment by drghnio** [comment]
then what about another button that toggles output or input

**Comment by bl4ckscor3** [comment]
As I said in my previous message: It's not possible to have both available at the same time, which is why this won't be a thing. The output is the one that's being prioritized here, because there's at least a manual way of toggling lasers.
