### ISSUE TITLE
Inventory scanner

### ISSUE THREAD

**Issue by GameWithNL** [Geforce132/SecurityCraft#273]
The inventory scanner doesn't work, if someone else is in it, I don't see if there are prohibited items in it.

**Comment by bl4ckscor3** [comment]
First and foremost: The inventory scanner ignores its owner (the owner is the player who placed down the scanner).

What do you mean by "someone else is in it"? Do you mean someone else is standing in the scanner field? Or do you mean that someone else is looking at the GUI?

**Comment by GameWithNL** [comment]
No, I mean there's someone in the scanner field.

**Comment by bl4ckscor3** [comment]
Ok. Does the Inventory Scanner have a Redstone Module or Storage Module installed so it can output a redstone signal/remove items from the inventory?

**Comment by GameWithNL** [comment]
No, because they don't work, it says that they don't work.

**Comment by bl4ckscor3** [comment]
Then the owner of the inventory scanner needs to add those modules so it can work.

**Comment by GameWithNL** [comment]
I did that, but it still doesn't work.

**Comment by bl4ckscor3** [comment]
As I said before, the inventory scanner will ignore its owner. It will work for other players.
Put a dirt block into one of the prohibited item slots. Make sure a storage module is installed. Put dirt blocks in your own inventory, and walk through. Observe that nothing happens. Let a different player who has dirt blocks in their inventory walk through the scanner field. Observe that the dirt blocks will be removed from that other player's inventory.
If the latter does not happen, please tell me the SecurityCraft version that you are using, as well as your Minecraft version.

**Comment by GameWithNL** [comment]
I cannot install the storage module. The version of minecraft is 1.17.1 and of security craft [1.17.1] SecurityCraft v1.8.23-beta4.jar.

**Comment by bl4ckscor3** [comment]
I can install the storage module just fine by rightclicking one of the inventory scanners with it. Are you sure this is your own inventory scanner?

**Comment by GameWithNL** [comment]
It says the Module is not modifiable, I'm sure I put it down and when I right-click on the inventory scanner with the module in my hand, nothing happens.

**Comment by GameWithNL** [comment]
And the admin tool doesn't work either, it says: The admin tool has been disabled through the config file.

**Comment by bl4ckscor3** [comment]
You can ignore "Module is not modifiable" for the storage module. It just means that the storage module needs no extra data to work. Rightclick the inventory scanner with a Universal Block Modifier and see if there is already a storage module in there. If not, put it into one of the slots. If yes, then I honestly do not know what you think the issue here is, even after all this discussion. I already explained that the inventory scanner ignores its owner (the player who placed down the scanner). I explained how to add modules, and noted that the scanner works for me as expected. If you cannot coherently tell me what exactly your issue is and how I can reliably reproduce it, I will close this issue because as far as I am concerned I cannot find anything wrong.

As for the admin tool: That message should really be self explanatory. The admin tool does not work because it has not been enabled... To enable it, set the `allowAdminTool` server configuration option to `true`.

**Comment by GameWithNL** [comment]
Oké thanks
