### ISSUE TITLE
1.12.2 Security Craft Crash on Startup

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [Geforce132/SecurityCraft#305]
Hi. I was playing on a custom modpack I made and just installed the latest version of Security craft, [1.12.2] SecurityCraft v1.9.0.2.jar, and my game crashed as soon as it tried to load the game.

Here is the crash report: https://pastebin.com/prZiauUv

Here is the Latest Log: https://paste.ee/p/oQulx

**Comment by bl4ckscor3** [comment]
As of SecurityCraft v1.9 the mod ships the mixin library to be able perform modifications on Minecraft's code itself. If you are using other mods that ship mixin, this issue can happen. That's why we upload an additional jar file for 1.12.2 that does not ship the mixin library. Instead, some other mod has to include it, which would either be MixinBootstrap, or in your case Phosphor.

https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3577171

Duplicate of #300
