### ISSUE TITLE
admin tool

### ISSUE THREAD

**Issue by Eltend** [Geforce132/SecurityCraft#312]
I didn't find the config to enable the admin tool

**Comment by bl4ckscor3** [comment]
This is a place to report bugs, not for support.

- For Minecraft 1.15.2 and above, there is a mod called Configured which allows you to edit configs ingame (if you don't want to use it, see the next bullet point): https://www.curseforge.com/minecraft/mc-mods/configured/files/all
- Alternatively (for Minecraft 1.14.4 and above), the server configuration file can be found at world/serverconfig/securitycraft-server.toml where world is the folder of your world. The client configuration file can be found in the config folder at the same place where your mods, resourcepacks, saves etc. folders are. It is named securitycraft-client.toml.
- For Minecraft 1.12.2, you can edit the config ingame. Otherwise the configuration file can be found in the config folder at the same place where your mods, resourcepacks, saves etc. folders are. It is named securitycraft.cfg.
