### ISSUE TITLE
Security Craft Crash with Aether 2

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [Geforce132/SecurityCraft#314]
So, I'm using this version of Security Craft for 1.12.2 (https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3577171) and the latest version of Aether 2 crashes when any mod that loads Mixen into the game is added. I would use the other version of Security Craft (https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3577164) but my game crashes with that one as well and it is completely unrelated to the problem I'm having now.

**Comment by bl4ckscor3** [comment]
Just using The Aether II and the no-mixin version of SecurityCraft does not crash my game. Please always include the corresponding crash report when you report a crash.
In any case, The Aether II uses mixin 0.8, while SecurityCraft needs to use Mixin 0.8, which means that SecurityCraft's mixins will not be loaded when The Aether II is installed. This can easily be fixed by installing the following mod alongside the no-mixin version of SecurityCraft: https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility
