### ISSUE TITLE
Camera and sentry issue (1.12.2)

### ISSUE THREAD

**Issue by greeklite** [Geforce132/SecurityCraft#321]
When i exit the camera system, The turrets disappear for me, the turret settings reset and they start shooting my friends. I have to reconnect and re-link my turrets again.
I can give a list of my mods if needed.

**Comment by bl4ckscor3** [comment]
A mod list as well as a video of the bug happening would be helpful.

**Comment by greeklite** [comment]
![image](https://user-images.githubusercontent.com/101646505/158403013-e6ce0913-71c6-483d-8afe-c39d5bc724ad.png)

**Comment by greeklite** [comment]
I will get the video of it happening when i get home

**Comment by greeklite** [comment]
https://user-images.githubusercontent.com/101646505/158471545-865ac0ac-9ebc-4775-9642-4cd0faa04248.mp4

**Comment by greeklite** [comment]
https://user-images.githubusercontent.com/101646505/158471713-0707e56a-a5ed-42bc-8b26-42a7eea2c3ba.mp4

**Comment by greeklite** [comment]
https://user-images.githubusercontent.com/101646505/158478027-5a8ab3f3-1146-4c52-b0e5-ae6d459100a6.mp4

sadly i cant record much more than a second because github doesnt allow me to upoad any longer than 2 second videos, but here is the bug in action.

**Comment by bl4ckscor3** [comment]
It's likely a file size limit, and not a length limit that is preventing you from uploading longer videos. Try uploading the recording to https://imgur.com, and post the link here. As it stands, the sentry disappearing is the only thing shown in the posted video, and that is part of a bug that _may_ be fixed in the next version of the mod. The more interesting part of this issue is the fact that sentries apparently lose their settings, which does not immediately seem to have a connection to the camera system. So having a visual reproduction of that happening could actually prove to be very helpful.

**Comment by greeklite** [comment]
https://imgur.com/a/J3lKSaM

**Comment by bl4ckscor3** [comment]
Thanks. This is weird, since the sentries disappearing is an error where the server does not tell the client about entities that exist. The sentries keep existing where they should be, even though you can't see them. Since shooting happens completely server side, these two should not affect each other (it looks more like the sentry settings got manually changed, since the sentries did not shoot the player they started shooting moments after). I'd like to hold off on this for this update, and ask you to check this again after we release v1.9.1 of the mod, to see if that fixes it. As I've mentioned above, there is a tentative fix for entities disappearing when existing a camera (see #317), so this _might_ be affected as well.

**Comment by greeklite** [comment]
alright. Thank you
