### ISSUE TITLE
Crash when attempting to craft reinforced iron bars & reinforced block of iron for Cage Trap

### ISSUE THREAD

**Issue by xBlackPoison357x** [Geforce132/SecurityCraft#333]
Crash when attempting to craft reinforced iron bars & reinforced block of iron for Cage Trap. Crashes as soon as I try and click the reinforced items to craft them.

[https://pastebin.com/QnHDaUZE](url)

**Comment by bl4ckscor3** [comment]
This looks to be a crash of JEI, not SecurityCraft.

**Comment by enigmaquip** [comment]
This is due to tabs that security craft adds to JEI, the crash only happens when it's one of your tabs

**Comment by bl4ckscor3** [comment]
That doesn't change the fact that the crash occured in JEI's code, not the code of SecurityCraft's recipe category. If it were caused by SC, then the crash would point to some code in SC, and not in JEI, or at least reference it in some way. Nonetheless, I can't reproduce it with JEI 5.7.0.196 and SecurityCraft v1.9.2 on Forge 40.1.31 anyway.
