### ISSUE TITLE
Crash When Looking At Reinforced Hopper Recipe in JEI

### ISSUE THREAD

**Issue by getBoolean** [Geforce132/SecurityCraft#337]
The game crashes if you look at the reinforced hopper recipe with JEI and Computer Craft: Tweaked is installed. It crashes for some other blocks too.

Crash Report: [crash-2022-06-17_22.21.59-client.txt](https://github.com/Geforce132/SecurityCraft/files/8932878/crash-2022-06-17_22.21.59-client.txt)

Downgrading Security Craft to v1.9.1 fixes the issue.

Minecraft 1.18.2
Security Craft v1.9.2
JEI v9.7.0.196
CC: Tweaked v1.100.6

**Comment by bl4ckscor3** [comment]
Duplicate of #333. This looks very much like a JEI bug. I am assuming, that downgrading SecurityCraft works, because we are using the outdated API in v1.9.1, and have updated to the new one in v1.9.2. Removing CC: Tweaked also gets rid of the issue. The crash happens in JEI's code, which has been changed with the introduction of the new API.

**Comment by getBoolean** [comment]
Thanks, I'll downgrade JEI then
