### ISSUE TITLE
Suggestion: Inventory Scanner- Return mode & Transfer Mode

### ISSUE THREAD

**Issue by CTH999** [Geforce132/SecurityCraft#346]
So, sometimes I don't want to destroy the items, but rather just not let some items on my base. So, my idea is as follows:

1. A mode on the [Scanner](https://github.com/Geforce132/SecurityCraft/wiki/Inventory-Scanner) that will save items by transferring them into a temporary inventory. One per player. So, if I block stone, and "Bob" comes in with 3 stone, "Nick" with 0, and "Steve" with 15, an inventory will be made linked to "Bob", then it will transfer the items there. Then, when going through that scanner again, those items are transfered back. if there's no room, they then get dropped on the ground. I recommend putting a hopper there!
2. Another feature is the "scanner frequency". This only appears in the "Save" mode. If you identical frequencies, the filters are set to be the same. And, if you walk through another it can give them back. So, I can have an "airport" (if you will). Walking thorugh a gate will remove weapons, but going through again returns them. After all, you can only go one way (It senses if you turned around, if so, takes them back!), so you can seamlessly confiscate then return at the other side! Now you can have multiple entrances, and never steal things.
3. Speaking of stealing things, maybe a mode that takes the confiscated items and puts them in an inventory behind it? Hey, you where warned! So, we are keeping your sword!

**Comment by bl4ckscor3** [comment]
You seem to be using a very outdated version of the mod. The Inventory Scanner no longer deletes items, and there are no different modes anymore. This behavior was changed a bit over 2 years ago in v1.8.18, and is now controled via modules. Because of this, your suggestions can't fully apply to the Inventory Scanner as it is now. You can add a storage module to the block to add an inventory where the items will be stored. This should be sufficient. The scanner has no "In" and "Out" concept, and adding one raises hard-to-solve questions about how to approach something like this.

**Comment by CTH999** [comment]
yeah, I can see how it could be an issue. Ah well, one can dream... one can dream...
