### ISSUE TITLE
Some sort of configuration with the breakability of blocks

### ISSUE THREAD

**Issue by cloby0** [Geforce132/SecurityCraft#348]
I saw an issue on here about configuring reinforced blocks, and although THEIR functionality won't be changed _(makes sense, it's their primary function and you can just crafttweaker/kubejs it out)_, a config for other blocks from the mod to become breakable would be nice for servers with a focus on PvP/factions.

(also if you do this because of this submission thingy can you please make a patch for 1.18.2 with this thank you a lot)

this is all a suggestion though

**Comment by bl4ckscor3** [comment]
The unbreakability applies to all blocks, and so does our stance on making it configurable.

Sidenote: We won't add something to the mod in a specific Minecraft version because someone asks for it, but because we are currently supporting (i.e. actively updating the mod for it) this Minecraft version. The currently supported ones are 1.12.2, 1.16.5, 1.17.1, 1.18.2, and 1.19.1. We will always try to add all additions/changes/fixes to all versions.
