### ISSUE TITLE
1.19 Minecraft Crashes when Trying to Prepare for World Generation

### ISSUE THREAD

**Issue by PilotgamerGuy** [Geforce132/SecurityCraft#355]
Log:
https://paste.ee/p/5Z4Gv

**Comment by bl4ckscor3** [comment]
This is not an issue caused by SecurityCraft, your game is missing libraries that it needs. This error should also happen if you do not have SecurityCraft installed. Try creating a new profile in MultiMC, reinstalling it, or using a different launcher altogether, like PolyMC (which is a fork of MultiMC).
