### ISSUE TITLE
Upgrading to Minecraft 1.9

### ISSUE THREAD

**Issue by guyfromhere** [Geforce132/SecurityCraft#36]
Hi,
your mod is incompatible to Minecraft 1.9, so it was my idea to change the required-version in your source code. So I changed in mod_SecurityCraft.java:34 the version from 1.8.8 to 1.9. But how do I compile the mod from the source code or are you planning to update the mod?

**Comment by bl4ckscor3** [comment]
First of all, you can't just change the required versions of the mod in order to make it work for the next MC version. Secondly, if you don't know how to build a Forge mod you shouldn't be messing around with mod source codes anyways. And yes, we will update SecurityCraft to 1.9.4, but only once v1.8.2 is out.

**Comment by guyfromhere** [comment]
Do you have a date for me when the 1.9-version will be released?

**Comment by bl4ckscor3** [comment]
No.
