### ISSUE TITLE
Inventory scanner problem

### ISSUE THREAD

**Issue by ForTyxx13** [Geforce132/SecurityCraft#382]
Hello, I recently noticed on versions 1.9.4 and 1.9.3.1 in Minecraft version 1.16.5 a problem. The problem is that the Inventory Scanner does not work. You can see the red barrier but even after applying the mods, they don't work. Like the redstone one that does not emit a redstone signal. Can you review this error and help me? Thank you

**Comment by bl4ckscor3** [comment]
This is intended. Your Inventory Scanner does not work because you are the owner of it and it ignores its owner. This is the case for many of SecurityCraft's blocks; They will still work for players that are not the owner. For what it's worth, there will be a Universal Block Modifier option next update to turn that off per block.
