### ISSUE TITLE
Out of nowhere crash "Exception ticking world" (1.16.5)

### ISSUE THREAD

**Issue by miel8** [Geforce132/SecurityCraft#390]
My Server crashes out of nowhere again and again. I figured this was a Issue with SecurityCraft since the only thing hinting at any mod is a mention of a Securitycraft mixin somewhere in the crash.

Crash report:
https://pastebin.com/yYUtVj77

**Comment by bl4ckscor3** [comment]
After looking into it, our conclusion is that this is very likely not caused by SecurityCraft. The part of the code the crash occurs in is not modified by us, and we do not have code that interacts with that part either. The reason why SecurityCraft shows up in the log is because we use Mixin to modify the file where the crash occurs in.
If you can reproduce this crash with a minimal amount of mods that include SecurityCraft, please reply with the reproduction steps. Until then, we will consider this as not caused by us.

**Comment by miel8** [comment]
Okay, thank you for your time.
