### ISSUE TITLE
[BUG] UI Bug

### ISSUE THREAD

**Issue by Ucritgamesin27** [Geforce132/SecurityCraft#397]
![image](https://user-images.githubusercontent.com/95477088/221335322-617b220f-b4ce-49d2-9d84-613508f1de77.png)
UI Bugged im playing in minecraft server 1.19.3 suddenly the ui securit craft got bugged hosting with aternos

**Comment by Geforce132** [comment]
I'm assuming that you also have Optifine installed? If so, try removing it and seeing if the issue goes away then.

**Comment by Ucritgamesin27** [comment]
> I'm assuming that you also have Optifine installed? If so, try removing it and seeing if the issue goes away then.
Oh yeah i have optifine installed but in 1.19.2 with optifine it works

**Comment by Ucritgamesin27** [comment]
So is there a way to do this with optifine

**Comment by Geforce132** [comment]
Not at the moment as it's an Optifine bug. Wait until a fix is released (or play on an older version of Forge). The pre5 version of Optifine says that it's compatible with Forge 44.1.17 when it, in fact, isn't ([ref](https://optifine.net/changelog?f=preview_OptiFine_1.19.3_HD_U_I2_pre5.jar)). Maybe try Rubidium instead of Optifine in the meantime?
