### ISSUE TITLE
Suggestion: Permission remote changers

### ISSUE THREAD

**Issue by MCTF-Alpha-27** [Geforce132/SecurityCraft#401]
It can change the permission level of the Keycard Reader remotely, and it would be better if we could do this in batches

**Comment by bl4ckscor3** [comment]
Thanks for your suggestion. However. we don't see a reason why changing the keycard levels remotely would be helpful. If the system is used properly, players won't need to do that. The keycard readers are set to the correct levels, the correctly levelled cards are given out to anyone who should gain access, and that's it. And adding a remote for one setting of one block means we also would need to add capability to change other settings, and the settings of other blocks. It does make sense for the mines and sentries also because of the ability to completely disable them momentarily, but we don't think changing the actual settings of blocks is necessary.
