### ISSUE TITLE
crash when placing any block

### ISSUE THREAD

**Issue by Aloncheeto** [Geforce132/SecurityCraft#418]
`The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Tag securitycraft:can_interact_with_doors used before it was bound` is the error i get in the minecraft launcher, i have no idea what this means, please help

**Comment by bl4ckscor3** [comment]
Please post the full log.

**Comment by Aloncheeto** [comment]
[latest.log](https://github.com/Geforce132/SecurityCraft/files/11256470/latest.log)
i guess this is what you are talking about?

**Comment by Aloncheeto** [comment]
hello?

**Comment by bl4ckscor3** [comment]
> i guess this is what you are talking about?

Yes, thank you. You are using an outdated version of SecurityCraft (v1.9.4). Please update to [the latest version (v1.9.6.1)](https://www.curseforge.com/minecraft/mc-mods/security-craft/files/4457714), and report back.
> hello?

I did not reply because I went to sleep. You cannot expect people to always reply to you when you want them to, please respect that they have lives as well and cannot be there just for you 24/7.

**Comment by Aloncheeto** [comment]
while the new version does not fix this, i found that going to a survival world, placing a block, logging out of the world, and connecting to the server, fixes the crash.

**Comment by Aloncheeto** [comment]
the problem was with the server not starting some script, it seems. its fixed now, thanks for trying to help!
