### ISSUE TITLE
EMC values not being set

### ISSUE THREAD

**Issue by darthvader45** [Geforce132/SecurityCraft#420]
Currently using 1.9.5 for 1.12.2, with Forge 14.23.5.2860.  If 1.12.2 is no longer supported, I understand, but it seems a bit annoying that the EMC feature is not working as it should (had to set EMC manually).

**Comment by bl4ckscor3** [comment]
EMC values are being set properly using Minecraft 1.12.2, Forge 14.23.5.2860, SecurityCraft v1.9.5, and ProjectE 1.4.1. Is there any specific block that is missing EMC that should have it?

**Comment by darthvader45** [comment]
For me it was practically all of them.

**Comment by bl4ckscor3** [comment]
🤷 Any other mods you have installed? You could try uninstalling them to see which one may be interfering, if any.

https://user-images.githubusercontent.com/5149876/235315334-ddbf00be-6e29-456b-a6ee-ba7e9ecb4d7c.mp4

**Comment by darthvader45** [comment]
Hmmm, the only other mods affecting EMC would be ProjectE Integrations and Expanded Equivalence.  I'll test without them and see if this still happens.

**Comment by bl4ckscor3** [comment]
Ah, that makes sense. We explicitly disable our own integration when ProjectE Integration is installed, because [they add integration as well](https://github.com/TagnumElite/ProjectE-Integration/blob/1.12.x/Plugins/Misc/src/main/java/com/tagnumelite/projecteintegration/plugins/misc/PluginSecurityCraft.java). I was under the impression that it is complete, but apparently it is not. We'll make sure ours is always enabled then - it will be present in the next update of SecurityCraft.

**Comment by darthvader45** [comment]
Thanks.  Will be quite useful for quick replication of reinforced blocks, making the reinforcer much easier to get to if I lose mine for some random reason (death, lava, etc.)
