### ISSUE TITLE
Bug in newest Version (1.9.7 for MC 1.12.2) of Security Caft Mod with the Display Case by Placing on a Block

### ISSUE THREAD

**Issue by TitooTVGeilo** [Geforce132/SecurityCraft#435]
Hi,
I have a bug found what you can Simple can found. Then you in the Display Case place on the Ground or on a block the Display Case have on the first time a violet/black error Block and one second later is the right Texture load. I hope you can fix this. All other Blocks and Items work normal and load normal. And this Problem is only by Placing not in the Creative Tab. In the Creative Tabs was all Blocks and Item Textures load. I hope you can fix it and this 2 Picture help you.

![2023-06-23_16 18 57](https://github.com/Geforce132/SecurityCraft/assets/108121897/ed0a0edd-dda7-4861-a93b-7bdbb13dd8a2)
![2023-06-23_16 19 16](https://github.com/Geforce132/SecurityCraft/assets/108121897/743f702b-77f1-4aa3-b4f1-4301e9e69190)

Other Mods:
Xaeros_Minimap_23.5.0_Forge_1.12
XaerosWorldMap_1.30.5_Forge_1.12
xaeroplus-108-WM1.30.5-MM23.5.0
voicechat-forge-1.12.2-2.4.10
Fancier-Block-Particles-0.8-Dev-15
and ItemBorders-1.12.2-forge-1.2.0

**Comment by bl4ckscor3** [comment]
This is a mod-compatibility issue with Fancier Block Particles. Since the display case does not have a standard block model, FBP fails to properly display it during the place-down animation. You should be able to fix this by adding the display case to FBP's particle denylist - though I am not 100% sure how it works, so you'll have to ask its author.
