### ISSUE TITLE
the briefcase keeps reseting its self

### ISSUE THREAD

**Issue by Crossalaxz** [Geforce132/SecurityCraft#469]
### Issue description

most times when i open the briefcase it keeps reseting its self so i have to keep puting in the code 2 times and i think other people can make there own code on it and just steal the stuff i feel like this is a bug

### Minecraft version

1.20.1

### Forge version

47.1.0

### SecurityCraft version

v1.9.7-beta2

**Comment by bl4ckscor3** [comment]
I can't reproduce this. The briefcase opens every time as I expect it, with no extra code needing to be inserted or the code needing to be set up again. Do you have a recording of this happening?

**Comment by Crossalaxz** [comment]
i can get one one sec

**Comment by Crossalaxz** [comment]
can you send me your gmail or something bec the flie's to big

**Comment by Crossalaxz** [comment]
or i can send you mine

**Comment by Crossalaxz** [comment]
email me at githubisdumb947@gmail.com

**Comment by Geforce132** [comment]
Could you just upload the video to Youtube or something like Dropbox or Google Drive and post the link to it here? If the file is that big, it most likely won't attach to a normal email anyway.

**Comment by Crossalaxz** [comment]
0910 (1)(3).mov
<https://drive.google.com/file/d/1sbrsO2pallPE7wr_As3mj5vR4b83rF46/view?usp=drive_web>

**Comment by bl4ckscor3** [comment]
The file is not public.

**Comment by Crossalaxz** [comment]
try it now

**Comment by Crossalaxz** [comment]
So uh , did you look at it?

**Comment by bl4ckscor3** [comment]
I have now, yes. Please be patient, we are doing this in our free time and can't always check things instantly.
Your video has a cut right before this happened, hence I am unsure whether this issue is fabricated, or it actually happens. I have tried opening the briefcase numerous times in my offhand and in my main hand, yet got no luck in reproducing it. Did you at any point have a Universal Key Changer in your main hand while having the briefcase in your offhand and then rightclicked? This will reset the briefcase's code and is fully intentional.

**Comment by Crossalaxz** [comment]
no i didnt

**Comment by bl4ckscor3** [comment]
I'll leave this issue open in case anyone has more info.
