### ISSUE TITLE
Minecraft 1.12.2 Version 1.9.8 of SecurityCraft Crash then I put a Smart Modul in the Laserblock

### ISSUE THREAD

**Issue by Titoo8899** [Geforce132/SecurityCraft#476]
### Issue description

Hi,
in your Newest Version of SecurityCraft Mod 1.9.8 Crash the game then I put a Smart Modul in the Laserblock. I have with the Universal Block Reinforcer right click on the Laserblock make and the GUI open normal. Then I the Smart Modul in one of the first two Slots put, the game Freeze and Crash. I hope you can fix it and a Massage ingame add who only say this it is not for Smart Modul. This Bug is Only in the newest Version in the last versions was it not or have I not look.

The Bug comes only from your mod the Other Mods what in the Mods Folder was is all Save and Bug free. I hope with the Crash Report and the Steps can you reüroduce the 1.12.2 Bug in the Newest Version of your Mod.

### Steps to reproduce

- Load the Game with the Mod
- Open a World
- Place a Laserblock
- Right Click with a Universal Block Reinforcer on the Laserblock
- Put a Smart Modul on the First or the Second Slot of the GUI what opens
- The Game Freeze and Crash

### Minecraft version

1.12.2

### Forge version

1.12.2 - 14.23.5.2860

### SecurityCraft version

v1.9.7.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Titoo8899/f9f89513ef5aa626a80bc894de767448

**Comment by bl4ckscor3** [comment]
I can't get it to crash with the reproduction steps. The crash report you linked also does not match the reported issue, however it shows another issue that I can reproduce and will fix.

**Comment by Titoo8899** [comment]
Oh okay then is the Problem what I have write not to 100% reproduce for all People

**Comment by Titoo8899** [comment]
And her a Videolink who I the Bug reproduce: https://www.youtube.com/watch?v=qa40cPTTJc8

**Comment by bl4ckscor3** [comment]
There's nothing different in those logs.

I noticed in the video that you are using a Universal Block **Reinforcer**. That is the incorrect tool for adding modules to a block, you need to use the Universal Block **Modifier** to do that. This confusion also explains why I am not getting a crash with the reproduction steps, and why the crash report you posted is the only one you have. The bug turns out to have nothing to do with the laser block or smart module.

Issue fixed in 75a69dc6bb16f4271b788cefd7f6345729a788d7 and I will release an update momentarily. Thank you for reporting!
