### ISSUE TITLE
when I put lasers in SecurityCraft mode it is just white and the redstown signal does not

### ISSUE THREAD

**Issue by Pukichkin** [Geforce132/SecurityCraft#485]
### Issue description

I just put the laser at a distance of 1 block and it turns white and does not work also happens with the Inventory Scanner

### Steps to reproduce

1 I will install the laser 2 it does not work

### Minecraft version

1.12.2

### Forge version

Forge 1.12.2

### SecurityCraft version

v1.9.8

**Comment by bl4ckscor3** [comment]
All of this is entirely intentional. 
**White lasers:** v1.9.8 of SecurityCraft introduced a new cosmetic feature allowing players to change the color of lasers etc. This is done by coloring a Lens item, rightclicking the block, and placing the lens into the respective slot. To get back the red color, craft a lens from red stained glass panes, or color it with red dye.
**Not working:** This can have two reasons:
1. SecurityCraft's blocks have an ownership system. Once you place down a SecurityCraft block, it is owned by you. Many blocks that have additional functionality (e.g. the Inventory Scanner taking out items from the player's inventory) ignore their owner. This can be turned off by rightclicking the block with a Universal Owner Changer, and setting the "Ignore Owner" option to false (This option is available in version v1.9.5 and later).
2. You need to add modules for functionality. The laser for instance only outputs a redstone signal if a redstone module is installed.
