### ISSUE TITLE
[Mod compat] SRParasites incompatibility 1.12.2

### ISSUE THREAD

**Issue by MiniRaptor** [Geforce132/SecurityCraft#507]
### Issue description

So, i've played Security Craft with Scape and Run: Parasites mod, and there one non critical but very annoying and problematic issue. 

On 7 phase of parasites borns a node and it begins to infect biomes. And this parasite biome has a property that turns all mobs in this biome into parasites over time, so here issue appears. Sentry's in security craft are mobs itself, so with time all sentry's in my house turned into parasites, and it's for the lack of better word destroyed my ass. Also there glitch, when sentry dies, it's collision still exists and can't be destroyed. 

I know that the developers know better how to make their mod. But maybe you could make the turrets from your mod be blocks and not mobs? I think it would fix a lot of problems...

### Steps to reproduce

1. Wait for 7 phase of parasites, or set it by /srpevolution setphase 7
2. Wait until node spawns and start growing parasite biome
3. Spawn sentry's in infected biome and wait until they will turn into parasites

### Minecraft version

1.12.2

### Forge version

2860

### SecurityCraft version

v1.9.9

### Other relevant versions

Scape and Run: Parasites 1.9.20: https://www.curseforge.com/minecraft/mc-mods/scape-and-run-parasites

**Comment by bl4ckscor3** [comment]
Thank you for this detailed report! I believe if you add `securitycraft:sentry` to the `COTH Mob Immune Mob List` config in `SRParasitesSystems.cfg`, this issue will be solved.

As for the collision staying: While I agree this is not an ideal solution, you can stand on top of the collision and run `/setblock ~ ~-1 ~ air` to remove it.

> I know that the developers know better how to make their mod. But maybe you could make the turrets from your mod be blocks and not mobs? I think it would fix a lot of problems...
Sentries need to be mobs because they use the same system to attack other mobs as for instance zombies do.
