### ISSUE TITLE
Trying to create a texture/resource pack

### ISSUE THREAD

**Issue by PlatCat** [Geforce132/SecurityCraft#508]
### Issue description

Hello I am trying to create a texture/resource pack for securitycraft but ive run into a bit of a hurdle. I have created texture/resource pack for minecraft prior but never for mods.

Ive noticed that in many cases textures have been ripped directly from minecraft instead of creating original ones eg. Redstone & speed module, many machines use dispenser or iron block textures, crystal quartz are just quartz with a hue, etc, etc. But no matter how many files I read I cannot figure out how theyre ripped (not proficent with coding). 
And since Im looking to change these textures that is a problem, how would one go to do so? Also where is the code that gives crystal quartz and reinforced blocks their hue?

I know that this isnt really a bug or anything like that aswell as an odd question but if someone could tell me what im doing wrong that would be deeply appreciated.
Thx in advance!

### Minecraft version

1.20.1

### Forge version

47.2.0

### SecurityCraft version

v1.9.9

**Comment by bl4ckscor3** [comment]
Creating resource packs for mods is no different than creating ones for Minecraft. SecurityCraft doesn't exactly rip the vanilla textures, it simply makes use of them. As you can see [here](https://github.com/Geforce132/SecurityCraft/blob/1.20/src/main/resources/assets/securitycraft/models/block/reinforced_stone.json#L4), we reference the vanilla stone instead of our own in the reinforced stone's block model. This is the case for pretty much all the instances where you see vanilla textures being used. If you change the vanilla texture, the reinforced block's texture will also be changed. Of course you can also change the reinforced block's model to reference your own texture. 
This is similar to the [speed module](https://github.com/Geforce132/SecurityCraft/blob/1.20/src/main/resources/assets/securitycraft/models/item/speed_module.json). It just uses two texture layers; One for the module background, and one for the sugar. Again, you can simply change the item module to change the texture.

As for reinforced block tint: This uses the same system as for instance vanilla grass blocks and leaves use to change color based on the biome they're in. This is done in code [here](https://github.com/Geforce132/SecurityCraft/blob/1.20/src/main/java/net/geforcemods/securitycraft/ClientHandler.java#L470-L658), and also needs a tintindex defined in the model files. This is done in the parent models of reinforced blocks, for example for reinforced stone this is done [here](https://github.com/Geforce132/SecurityCraft/blob/1.20/src/main/resources/assets/securitycraft/models/block/reinforced_block.json). This is not the only file where this is done. Some blocks use different ones, but the method is always the same. If you do not want the tint, then you have two options:
1. Disable it in the config file of the mod (not possible with the resource pack)
2. Replace all the parent block models that define a tintindex with versions of themselves that have the tintindex removed. With this you have to watch out that you only remove the tintindex that defines reinforced block tinting, and not the one that for instance makes sure reinforced grass changes color based on biome.

And finally, as you've correctly noted, this is an issue tracker, not a place for suggestions or to get help. This is also shown to you when you [create a new issue](https://github.com/Geforce132/SecurityCraft/issues/new/choose). If you need further assistance with this, feel free to join our Discord server and we'll be happy to continue there.

**Comment by PlatCat** [comment]
thanks alot, this will hopefully help
