### ISSUE TITLE
Game Crashes when attempting to place Panic Button on fence

### ISSUE THREAD

**Issue by NoobDancer100** [Geforce132/SecurityCraft#513]
### Issue description

I was messing around with SecurityCraft and I managed to get a reproducable crash when attempting to place a panic button on a fence with specific conditions.

Video: https://youtu.be/PRG-WIlDK5s

### Steps to reproduce

1. Place two fences (or walls), one on top of the other, make sure there are no other blocks near the top one
2. Place the Panic Button on the top fence (on a side with no blocks to fall back to)
3. Game Crashes

### Minecraft version

1.20.1

### Forge version

47.2.0

### SecurityCraft version

v1.9.9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/NoobDancer100/7913b2e7e92a85e5c1757e3252ec3c56

**Comment by bl4ckscor3** [comment]
Thank you for this great and detailed report! We fixed a crash in 03af16221d80aa3fd42a7760ba71a2b7144cf4f2 that happened when the panic button was placed on powdered snow, which is actually the same as this one. Since powdered snow doesn't exist below 1.17, we did not fix this for 1.12.2 and 1.16.5, so in that sense this report has helped us realize we need to fix it for those version as well. Many thanks!
